[package]
name = "cendre"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = "1.0.70"
ash = { git = "https://github.com/ash-rs/ash.git", rev = "77e614d7766b17ef06c441ad28b419fed1329d07", features = [
    "linked",
    "debug",
] }
ash-window = { git = "https://github.com/ash-rs/ash.git", rev = "77e614d7766b17ef06c441ad28b419fed1329d07" }
bevy = { version = "0.10.1", default-features = false, features = [
    "bevy_winit",
    "bevy_asset",
    "bevy_render",
    "filesystem_watcher",
] }
bytemuck = "1.13.1"
# gpu-allocator = "0.22.0"
# Use a patched version that uses the git version of ash
gpu-allocator = { path = "../gpu-allocator" }
meshopt = "0.1.9"
naga = { version = "0.11.0", features = ["wgsl-in", "spv-out", "glsl-in"] }
raw-window-handle = "0.5.2"
tobj = { version = "3.2.5", features = ["async"] }
winit = "0.28.3"
